version: '3'
services:
    app:
        container_name: welltech-app
        build:
            context: .
            dockerfile: docker/php-fpm/Dockerfile
        volumes:
            - .:/var/www/
        networks:
            - welltech-app
    nginx:
        image: nginx:alpine
        container_name: nginx-welltech
        ports:
            - "8082:80"
        volumes:
            - ./:/var/www:cached
            - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
            - ./docker/nginx/logs:/var/log/nginx
        depends_on:
            - app
            - db
        networks:
            - welltech-app
    db:
        image: mariadb:10.3.24
        container_name: welltech-db
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: welltech
            MYSQL_USER: laravel
            MYSQL_PASSWORD: secret
        volumes:
            - ./docker/mysql:/var/lib/mysql
        ports:
            - 3311:3306
        networks:
            - welltech-app
    redis:
        image: redis:latest
        ports:
            - 6388:6379
        volumes:
            - ./docker/redis:/data
        networks:
            - welltech-app
networks:
  welltech-app:
